[package]
name = "sp1-ics07-tendermint-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-sol-types = "0.7.2"
tendermint-light-client-verifier = { version = "0.36.0", default-features = false }
serde = { version = "1.0", default-features = false }
