name: Program

on: 
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          source /home/runner/.bashrc
          sp1up 
          cargo-prove prove --version

      - name: Build SP1 program
        run: |
          cd program
          cargo-prove prove build --release
